name: Greeting from The Fastcampus
on: workflow_dispatch
env:
  BUILD_NUMBER: ${{ github.run_number }}

jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
      - name: Call Global ENV
        run: echo "Build Number -> $BUILD_NUMBER"
      - name: Print a greeting - 1
        env:
          MY_VAR: Hi there! My name is
          FIRST_NAME: JinHo
          MIDDLE_NAME: The
          LAST_NAME: Fastcampus
        run: |
          echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME
      - name: Print a greeting - 2
        run: |
          echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME
